### ISSUE TITLE
luna-console 可选链写法出现在vue中报错

### ISSUE THREAD

**Issue by suoxins** [liriliri/luna#6]
您好 luna-console作者

luna-console 可选链写法出现在vue中报错 报错内容如下：
 
![image](https://user-images.githubusercontent.com/64819817/216869018-668e3136-6b38-493a-b4e1-c6f29003c1bf.png)

已安装支持插件
 
![image](https://user-images.githubusercontent.com/64819817/216869029-3abd5d0a-9f57-41e7-8946-5bffe4a41dda.png)

编译后仍然报错
 
![image](https://user-images.githubusercontent.com/64819817/216869045-81601c2a-0fdb-4c18-a49d-1457801c8126.png)

还请大佬指点一下！感谢

**Comment by surunzi** [comment]
这个配置下对 luna-console 进行处理应该就可以了，参照 https://github.com/liriliri/eruda 可以转换成 es5。

**Comment by suoxins** [comment]
> 这个配置下对 luna-console 进行处理应该就可以了，参照 https://github.com/liriliri/eruda 可以转换成 es5。

谢谢
