### ISSUE TITLE
[luna-console] indistinguishable log levels `log` & `info`

### ISSUE THREAD

**Issue by ManiaciaChao** [liriliri/luna#7]
## Bugs

Currently,`luna-console` shares the same implementation between log method `log` & `info`, making them technically indistinguishable by a human or a filter function. Developers need extra logic to implement their own log filter.

https://github.com/liriliri/luna/blob/0c71e214f320c5e29aeb1ec42f8e549cfea065f0/src/console/index.ts#L198-L202

https://github.com/liriliri/luna/blob/0c71e214f320c5e29aeb1ec42f8e549cfea065f0/src/console/index.ts#L261-L265

## Solution

**Comment by surunzi** [comment]
Fixed in version 1.3.1
